import { BUDGET_CHOICES, OWNER, pageMetadata, SERVICE_CHOICES } from "@/lib/content";

export const metadata = pageMetadata("/contact/", "Contact", "Get in touch with LONG SENGCHHUN about a design, video, photography, or 3D project.");

export default async function ContactPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const sent = params.sent === "1";
  const emailSent = params.email === "sent";
  const error = typeof params.error === "string" ? params.error : "";
  const requestedService = typeof params.service === "string" && SERVICE_CHOICES.includes(params.service as never) ? params.service : "";
  return <><section className="page-hero compact"><div className="container"><p className="eyebrow">Contact</p><h1>Tell me what you want to create.</h1><p>Share the project, timeline, and what success should look like. I will reply using your preferred contact details.</p></div></section>
    {sent && <div className="success-celebration" data-success-celebration role="dialog" aria-modal="true" aria-labelledby="contact-success-title" aria-describedby="contact-success-message"><div className="success-card"><button type="button" className="success-close" data-success-close aria-label="Close confirmation dialog">&times;</button><span className="success-check" aria-hidden="true" /><p className="eyebrow">Message received</p><h2 id="contact-success-title">Thank you for your project inquiry.</h2><p className="khmer-line" id="contact-success-message" lang="km">សំណើគម្រោងរបស់លោកអ្នកត្រូវបានផ្ញើដោយជោគជ័យ។</p><p className="success-email-state"><i className={`bi ${emailSent ? "bi-envelope-check" : "bi-clock-history"}`} />{emailSent ? "A confirmation email is now in your inbox." : "Your request is saved and ready for review."}</p><div className="success-actions"><button className="btn btn-accent" type="button" data-success-continue>Continue</button></div><small className="success-hint">The voice confirmation plays automatically. You can also press Escape or click outside this message.</small><audio id="contactSuccessAudio" preload="auto"><source src="/static/audio/contact-success-khmer.m4a" type="audio/mp4" /></audio></div></div>}
    <section className="section pt-0"><div className="container contact-grid"><aside className="contact-sidebar"><p className="eyebrow">Direct Contact</p><a href={`mailto:${OWNER.email}`}>{OWNER.email}</a><a href={`tel:${OWNER.phone}`}>{OWNER.phone}</a><a href={OWNER.telegramUrl} target="_blank" rel="noreferrer">Telegram {OWNER.telegram}</a><span>{OWNER.location}</span><p className="muted">Budget ranges are only a starting point for discussion, not fixed prices.</p></aside>
      <form className="inquiry-form" action="/api/inquiries/" method="post" encType="multipart/form-data">{error && <div className="alert alert-danger">{error === "rate" ? "Please wait a few minutes before sending another inquiry." : "Please check the form and try again."}</div>}<input type="text" name="honeypot" tabIndex={-1} autoComplete="off" className="visually-hidden" aria-hidden="true" />
        <div className="form-grid"><div className="form-field"><label htmlFor="full_name">Full name</label><input className="form-control" id="full_name" name="full_name" required maxLength={120} /></div><div className="form-field"><label htmlFor="email">Email</label><input className="form-control" id="email" name="email" type="email" required /></div><div className="form-field"><label htmlFor="phone_or_telegram">Phone or Telegram</label><input className="form-control" id="phone_or_telegram" name="phone_or_telegram" placeholder="Phone number or Telegram username" /></div><div className="form-field"><label htmlFor="company">Company</label><input className="form-control" id="company" name="company" /></div><div className="form-field"><label htmlFor="service_needed">Service needed</label><select className="form-select" id="service_needed" name="service_needed" required defaultValue={requestedService}><option value="" disabled>Select a service</option>{SERVICE_CHOICES.map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-field"><label htmlFor="estimated_budget">Estimated budget</label><select className="form-select" id="estimated_budget" name="estimated_budget" defaultValue=""><option value="">Select a budget</option>{BUDGET_CHOICES.map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-field full"><label htmlFor="preferred_timeline">Preferred timeline</label><input className="form-control" id="preferred_timeline" name="preferred_timeline" placeholder="Example: this week, next month, flexible" /></div><div className="form-field full"><label htmlFor="project_description">Project description</label><textarea className="form-control" id="project_description" name="project_description" rows={6} required minLength={10} placeholder="Tell me what you want to create." /></div><div className="form-field full"><label htmlFor="attachment">Attachment</label><input className="form-control" id="attachment" name="attachment" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.zip" /><small>PDF, image, WebP, or ZIP. Maximum 8 MB.</small></div><label className="form-check full"><input className="form-check-input" type="checkbox" name="consent" required /><span>I agree to be contacted about this project inquiry.</span></label></div>
        <button className="btn btn-accent" type="submit">Send Project Inquiry</button>
      </form>
    </div></section></>;
}
