// Best-effort auto-categorization for new products. Runs once, at product creation, only when
// the admin hasn't already picked a category — it never overrides a category chosen by hand,
// including an explicit "Uncategorized" on a later edit. Purely keyword-based (no external API,
// no extra cost, no network dependency) — good enough to save the admin a manual step on the
// common cases, with the existing category dropdown always there as the manual override.
//
// Naming follows the convention already used in this store's own categories (e.g. "3D
// Character", "Pchum Ben 3D Models"): a Cambodian cultural/local theme keeps its Khmer term
// (transliterated) in the name, everything else gets a plain English "3D <Type>" name. Category
// slugs are generated by the same DB function used everywhere else
// (`dashboard_upsert_product_category`), which strips non a-z0-9 characters — so this
// deliberately never proposes a name in Khmer script itself, only Khmer terms transliterated
// into Latin letters, to avoid producing a colliding/empty slug.

type ExistingCategory = { id: number; name: string; slug: string };
type CategorizationInput = { title: string; short_description?: string; tags?: string; file_formats?: string };

const CULTURAL_THEMES: { keywords: string[]; name: string }[] = [
  { keywords: ["pchum ben", "ancestor offering", "ancestors day"], name: "Pchum Ben 3D Models" },
  { keywords: ["khmer new year", "chol chnam", "sangkranta", "chaul chnam"], name: "Khmer New Year 3D Models" },
  { keywords: ["angkor wat", "angkor thom", "bayon"], name: "Angkor 3D Models" },
  { keywords: ["apsara"], name: "Apsara 3D Models" },
  { keywords: ["pagoda", "buddhist temple", "vihara"], name: "Pagoda 3D Models" },
  { keywords: ["khmer wedding"], name: "Khmer Wedding 3D Models" },
  { keywords: ["water festival", "bon om touk", "boat racing festival"], name: "Water Festival 3D Models" },
  { keywords: ["royal palace"], name: "Royal Palace 3D Models" },
  { keywords: ["sampot", "khmer costume", "khmer traditional dress"], name: "Khmer Costume 3D Models" },
  { keywords: ["krama"], name: "Krama 3D Models" },
];

const GENERIC_TYPES: { keywords: string[]; name: string }[] = [
  { keywords: ["character", "human model", "avatar", " npc", "humanoid"], name: "3D Character" },
  { keywords: ["vehicle", " car ", "car model", "truck", "motorbike", "motorcycle", " bike", "tuk tuk", "tuktuk"], name: "3D Vehicle" },
  { keywords: ["furniture", "chair", "sofa", "cabinet", "wardrobe", "bookshelf", " desk", "dining table", "coffee table"], name: "3D Furniture" },
  { keywords: ["architecture", "building", "house model", "interior design", "exterior design", "floor plan"], name: "3D Architecture" },
  { keywords: ["weapon", " gun ", "rifle", "pistol", "sword", "knife model"], name: "3D Weapon" },
  { keywords: ["environment", "landscape", "terrain", "forest scene", "nature scene"], name: "3D Environment" },
  { keywords: [" prop ", "props pack", "hand prop"], name: "3D Props" },
  { keywords: ["animal", "creature", " dog ", " cat ", "bird model"], name: "3D Animal" },
  { keywords: ["food model", "fruit model", "drink model", "dessert model"], name: "3D Food" },
  { keywords: ["robot", "mecha", "mech suit", "droid"], name: "3D Robot" },
  { keywords: ["sci-fi", "sci fi", "scifi", "spaceship", "space station"], name: "Sci-Fi 3D Models" },
  { keywords: ["low poly", "lowpoly", "low-poly"], name: "Low Poly 3D Models" },
  { keywords: ["electronics", "smartphone model", "laptop model", "gadget model"], name: "3D Electronics" },
  { keywords: ["clothing", "fashion model", "dress model", "shirt model", "outfit model"], name: "3D Fashion" },
];

function normalize(text: string) {
  return ` ${text.toLowerCase().replace(/\s+/g, " ")} `;
}

function slugify(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function scoreMatch(haystack: string, keywords: string[]) {
  let score = 0;
  for (const keyword of keywords) if (haystack.includes(keyword.toLowerCase())) score += keyword.trim().length;
  return score;
}

export function suggestCategory(input: CategorizationInput, existing: ExistingCategory[]): { categoryId: number } | { newCategoryName: string } | null {
  const haystack = normalize([input.title, input.short_description, input.tags, input.file_formats].filter(Boolean).join(" "));
  if (haystack.trim().length < 2) return null;

  // 1. Reuse an existing category if its own name is already implied by the product's text —
  // keeps the catalog from fragmenting into near-duplicate categories over time.
  let bestExisting: { id: number; score: number } | null = null;
  for (const category of existing) {
    const words = category.name.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2 && w !== "3d" && w !== "models");
    const score = scoreMatch(haystack, words);
    if (score > 0 && (!bestExisting || score > bestExisting.score)) bestExisting = { id: category.id, score };
  }
  if (bestExisting) return { categoryId: bestExisting.id };

  // 2. A Cambodian cultural/seasonal theme is more specific than a generic asset type, so it's
  // checked first.
  const themeMatch = pickBest(haystack, CULTURAL_THEMES) ?? pickBest(haystack, GENERIC_TYPES);
  if (!themeMatch) return null;

  const existingBySlug = existing.find((c) => c.slug === slugify(themeMatch));
  return existingBySlug ? { categoryId: existingBySlug.id } : { newCategoryName: themeMatch };
}

function pickBest(haystack: string, table: { keywords: string[]; name: string }[]) {
  let best: { name: string; score: number } | null = null;
  for (const entry of table) {
    const score = scoreMatch(haystack, entry.keywords);
    if (score > 0 && (!best || score > best.score)) best = { name: entry.name, score };
  }
  return best?.name ?? null;
}
