# Generated by Django 6.0.5 on 2026-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinquiry',
            name='service_needed',
            field=models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Poster Design', 'Poster Design'), ('Video Editing', 'Video Editing'), ('Photography', 'Photography'), ('Videography', 'Videography'), ('Filmmaking', 'Filmmaking'), ('3D Modeling', '3D Modeling'), ('3D Animation', '3D Animation'), ('Motion Graphics', 'Motion Graphics'), ('Social Media Content', 'Social Media Content'), ('Other', 'Other')], max_length=80),
        ),
    ]
