# Generated by Django 6.0.5 on 2026-07-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projectinquiry_service_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinquiry',
            name='service_needed',
            field=models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Poster Design', 'Poster Design'), ('Video Editing', 'Video Editing'), ('Photo / Video Production', 'Photo / Video Production'), ('Photography', 'Photography'), ('Videography', 'Videography'), ('Filmmaking', 'Filmmaking'), ('3D Design and Modeling', '3D Design and Modeling'), ('3D Modeling', '3D Modeling'), ('3D Animation', '3D Animation'), ('Product Visualization', 'Product Visualization'), ('Motion Graphics', 'Motion Graphics'), ('Social Media Content', 'Social Media Content'), ('Other', 'Other')], max_length=80),
        ),
    ]
