# Generated by Django 6.0.5 on 2026-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projectinquiry_service_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, upload_to='projects/videos/'),
        ),
        migrations.AddField(
            model_name='projectgalleryitem',
            name='video_file',
            field=models.FileField(blank=True, upload_to='projects/gallery/videos/'),
        ),
    ]
