# Generated by Django 6.0.5 on 2026-07-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_project_video_file_projectgalleryitem_video_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=80)),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("referrer", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, db_index=True, max_length=40)),
                ("device_model", models.CharField(blank=True, max_length=120)),
                ("browser", models.CharField(blank=True, max_length=80)),
                ("os", models.CharField(blank=True, max_length=80)),
                ("platform", models.CharField(blank=True, max_length=120)),
                ("language", models.CharField(blank=True, max_length=40)),
                ("timezone", models.CharField(blank=True, max_length=80)),
                ("screen_width", models.PositiveIntegerField(blank=True, null=True)),
                ("screen_height", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="projectinquiry",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectinquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewing", "Reviewing"),
                    ("replied", "Replied"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("archived", "Archived"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectinquiry",
            name="estimated_budget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not decided yet", "Not decided yet"),
                    ("Under $100", "Under $100"),
                    ("$100-$300", "$100-$300"),
                    ("$300-$700", "$300-$700"),
                    ("$700-$1,500", "$700-$1,500"),
                    ("Above $1,500", "Above $1,500"),
                    ("Prefer to discuss privately", "Prefer to discuss privately"),
                ],
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="khmer_intro",
            field=models.CharField(
                blank=True,
                default="បង្កើតស្នាដៃដែលភ្ជាប់ជាមួយគំនិត​និង ការរចនា របស់លោកអ្នកជាមួយយើងឥឡូវនេះ",
                max_length=255,
            ),
        ),
    ]
