create extension if not exists pgcrypto with schema extensions;

create table public.site_settings (
  id bigint generated by default as identity primary key,
  site_name varchar(120) not null default 'LONG SENGCHHUN',
  professional_title varchar(160) not null default 'Multidisciplinary Creative Designer',
  hero_intro text not null,
  khmer_intro varchar(255) not null default '',
  professional_intro text not null default '',
  portrait text not null default '',
  showreel_title varchar(160) not null default '',
  showreel_thumbnail text not null default '',
  youtube_url text not null default '',
  vimeo_url text not null default '',
  local_video_url text not null default '',
  email varchar(254) not null default 'longsengchhun@gmail.com',
  phone varchar(40) not null default '016 590 899',
  location varchar(120) not null default 'Phnom Penh, Cambodia',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.social_links (
  id bigint generated by default as identity primary key,
  label varchar(60) not null,
  url text not null,
  icon_name varchar(60) not null default '',
  "order" integer not null default 0 check ("order" >= 0),
  is_active boolean not null default true
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  slug varchar(90) not null unique,
  "order" integer not null default 0 check ("order" >= 0)
);

create table public.projects (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  title varchar(180) not null,
  slug varchar(200) not null unique,
  year integer not null check (year between 1900 and 2200),
  short_description varchar(420) not null,
  project_type varchar(120) not null default '',
  cover_image text not null default '',
  cover_video_url text not null default '',
  video_file text not null default '',
  client varchar(160) not null default '',
  role varchar(180) not null default '',
  project_duration varchar(80) not null default '',
  software_used varchar(255) not null default '',
  introduction text not null default '',
  objective text not null default '',
  creative_approach text not null default '',
  process text not null default '',
  final_result text not null default '',
  embedded_video_url text not null default '',
  before_image text not null default '',
  after_image text not null default '',
  credits text not null default '',
  is_featured boolean not null default false,
  status varchar(20) not null default 'draft' check (status in ('draft', 'published')),
  "order" integer not null default 0 check ("order" >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index projects_status_order_idx on public.projects(status, "order", year desc);
create index projects_category_idx on public.projects(category_id);

create table public.project_gallery_items (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  item_type varchar(20) not null default 'image' check (item_type in ('image', 'video')),
  image text not null default '',
  video_url text not null default '',
  video_file text not null default '',
  caption varchar(220) not null default '',
  alt_text varchar(180) not null default '',
  layout varchar(20) not null default 'landscape' check (layout in ('landscape', 'portrait', 'full')),
  "order" integer not null default 0 check ("order" >= 0)
);

create table public.project_inquiries (
  id bigint generated by default as identity primary key,
  full_name varchar(120) not null,
  email varchar(254) not null,
  phone_or_telegram varchar(80) not null default '',
  company varchar(140) not null default '',
  service_needed varchar(80) not null,
  estimated_budget varchar(80) not null default '',
  preferred_timeline varchar(120) not null default '',
  project_description text not null,
  attachment text not null default '',
  consent boolean not null default false,
  ip_address inet,
  status varchar(20) not null default 'new' check (status in ('new', 'reviewing', 'replied', 'accepted', 'declined', 'archived')),
  admin_notes text not null default '',
  is_reviewed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index project_inquiries_created_idx on public.project_inquiries(created_at desc);
create index project_inquiries_ip_idx on public.project_inquiries(ip_address, created_at desc);

create table public.visitor_events (
  id bigint generated by default as identity primary key,
  session_key varchar(80) not null default '',
  path varchar(255) not null,
  referrer text not null default '',
  ip_address inet,
  user_agent text not null default '',
  device_type varchar(40) not null default '',
  device_model varchar(120) not null default '',
  browser varchar(80) not null default '',
  os varchar(80) not null default '',
  platform varchar(120) not null default '',
  language varchar(40) not null default '',
  timezone varchar(80) not null default '',
  screen_width integer check (screen_width is null or screen_width >= 0),
  screen_height integer check (screen_height is null or screen_height >= 0),
  viewport_width integer check (viewport_width is null or viewport_width >= 0),
  viewport_height integer check (viewport_height is null or viewport_height >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index visitor_events_created_idx on public.visitor_events(created_at desc);
create index visitor_events_session_idx on public.visitor_events(session_key);
create index visitor_events_path_idx on public.visitor_events(path);

alter table public.site_settings enable row level security;
alter table public.social_links enable row level security;
alter table public.categories enable row level security;
alter table public.projects enable row level security;
alter table public.project_gallery_items enable row level security;
alter table public.project_inquiries enable row level security;
alter table public.visitor_events enable row level security;

create policy "public reads site settings" on public.site_settings for select to anon, authenticated using (true);
create policy "public reads active social links" on public.social_links for select to anon, authenticated using (is_active);
create policy "public reads categories" on public.categories for select to anon, authenticated using (true);
create policy "public reads published projects" on public.projects for select to anon, authenticated using (status = 'published');
create policy "public reads published gallery" on public.project_gallery_items for select to anon, authenticated using (exists (select 1 from public.projects where projects.id = project_id and projects.status = 'published'));
create policy "public records visits" on public.visitor_events for insert to anon, authenticated with check (true);

grant usage on schema public to anon, authenticated;
grant select on public.site_settings, public.social_links, public.categories, public.projects, public.project_gallery_items to anon, authenticated;
grant insert on public.visitor_events to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portfolio-media', 'portfolio-media', true, 104857600, array['image/jpeg','image/png','image/webp','video/mp4','application/pdf','application/zip','application/x-zip-compressed'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "public reads portfolio media" on storage.objects for select to anon, authenticated using (bucket_id = 'portfolio-media');
create policy "public uploads inquiry attachments" on storage.objects for insert to anon, authenticated with check (bucket_id = 'portfolio-media' and (storage.foldername(name))[1] = 'inquiries');

create or replace function public.dashboard_token_ok(p_token text)
returns boolean language sql stable security definer set search_path = public, extensions
as $$ select encode(extensions.digest(coalesce(p_token, ''), 'sha256'), 'hex') = '67bc4385eb7bb6a52bcc29723d775a0d1343a13ba312a05b88b656ba2959d074' $$;

create or replace function public.submit_inquiry(
  p_full_name text, p_email text, p_phone_or_telegram text, p_company text,
  p_service_needed text, p_estimated_budget text, p_preferred_timeline text,
  p_project_description text, p_attachment text, p_ip_address inet
) returns bigint language plpgsql security definer set search_path = public
as $$
declare new_id bigint;
begin
  if p_ip_address is not null and exists (select 1 from project_inquiries where ip_address = p_ip_address and created_at > now() - interval '5 minutes') then
    raise exception 'rate_limited';
  end if;
  insert into project_inquiries (full_name, email, phone_or_telegram, company, service_needed, estimated_budget, preferred_timeline, project_description, attachment, consent, ip_address)
  values (left(trim(p_full_name),120), left(trim(p_email),254), left(trim(coalesce(p_phone_or_telegram,'')),80), left(trim(coalesce(p_company,'')),140), left(trim(p_service_needed),80), left(trim(coalesce(p_estimated_budget,'')),80), left(trim(coalesce(p_preferred_timeline,'')),120), p_project_description, coalesce(p_attachment,''), true, p_ip_address)
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.dashboard_snapshot(p_token text)
returns jsonb language plpgsql stable security definer set search_path = public
as $$
begin
  if not dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  return jsonb_build_object(
    'total_visits', (select count(*) from visitor_events),
    'today_visits', (select count(*) from visitor_events where created_at::date = (now() at time zone 'Asia/Phnom_Penh')::date),
    'unique_visitors', (select count(distinct session_key) from visitor_events),
    'new_inquiries', (select count(*) from project_inquiries where status = 'new'),
    'accepted_projects', (select count(*) from project_inquiries where status = 'accepted'),
    'latest_visits', coalesce((select jsonb_agg(to_jsonb(v)) from (select id, path, device_type, device_model, browser, os, screen_width, screen_height, created_at from visitor_events order by created_at desc limit 40) v), '[]'::jsonb),
    'latest_inquiries', coalesce((select jsonb_agg(to_jsonb(i)) from (select id, full_name, email, phone_or_telegram, company, service_needed, estimated_budget, preferred_timeline, project_description, attachment, consent, status, admin_notes, is_reviewed, created_at, updated_at from project_inquiries order by created_at desc limit 20) i), '[]'::jsonb),
    'device_breakdown', coalesce((select jsonb_agg(to_jsonb(d)) from (select device_type, count(*)::integer as total from visitor_events group by device_type order by total desc) d), '[]'::jsonb),
    'top_pages', coalesce((select jsonb_agg(to_jsonb(p)) from (select path, count(*)::integer as total from visitor_events group by path order by total desc limit 8) p), '[]'::jsonb)
  );
end $$;

create or replace function public.dashboard_inquiry(p_token text, p_id bigint)
returns jsonb language plpgsql stable security definer set search_path = public
as $$
declare result jsonb;
begin
  if not dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  select to_jsonb(i) into result from project_inquiries i where i.id = p_id;
  return result;
end $$;

create or replace function public.dashboard_update_inquiry(p_token text, p_id bigint, p_status text, p_admin_notes text, p_is_reviewed boolean)
returns boolean language plpgsql security definer set search_path = public
as $$
begin
  if not dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_status not in ('new','reviewing','replied','accepted','declined','archived') then raise exception 'invalid_status'; end if;
  update project_inquiries set status = p_status, admin_notes = coalesce(p_admin_notes,''), is_reviewed = p_is_reviewed, updated_at = now() where id = p_id;
  return found;
end $$;

grant execute on function public.submit_inquiry(text,text,text,text,text,text,text,text,text,inet) to anon, authenticated;
grant execute on function public.dashboard_snapshot(text) to anon, authenticated;
grant execute on function public.dashboard_inquiry(text,bigint) to anon, authenticated;
grant execute on function public.dashboard_update_inquiry(text,bigint,text,text,boolean) to anon, authenticated;
