-- 3D Store foundation: categories, products, preview media, purchasable files.
-- Mirrors the existing categories/projects/project_gallery_items pattern.
-- Purchasable files live in a PRIVATE bucket — never publicly readable.

create table public.product_categories (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  slug varchar(90) not null unique,
  "order" integer not null default 0 check ("order" >= 0)
);

create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.product_categories(id) on delete set null,
  title varchar(180) not null,
  slug varchar(200) not null unique,
  short_description varchar(420) not null default '',
  description text not null default '',
  price_usd numeric(10,2) not null default 0 check (price_usd >= 0),
  price_khr numeric(12,0) not null default 0 check (price_khr >= 0),
  tags text not null default '',
  software text not null default '',
  file_formats text not null default '',
  polygon_count varchar(40) not null default '',
  texture_info text not null default '',
  dimensions varchar(120) not null default '',
  file_size varchar(40) not null default '',
  version varchar(40) not null default '',
  license text not null default '',
  compatibility text not null default '',
  requirements text not null default '',
  notes text not null default '',
  cover_image text not null default '',
  preview_video text not null default '',
  viewer_model text not null default '', -- glb/gltf path in the PUBLIC bucket, for the interactive viewer
  is_featured boolean not null default false,
  status varchar(20) not null default 'draft' check (status in ('draft', 'published')),
  "order" integer not null default 0 check ("order" >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_status_order_idx on public.products(status, "order");
create index products_category_idx on public.products(category_id);

create table public.product_media (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  media_type varchar(20) not null default 'image' check (media_type in ('image', 'video')),
  file_path text not null default '',
  caption varchar(220) not null default '',
  "order" integer not null default 0 check ("order" >= 0)
);

create index product_media_product_order_idx on public.product_media(product_id, "order");

create table public.product_files (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  file_name varchar(255) not null,
  file_path text not null,
  file_size bigint,
  "order" integer not null default 0 check ("order" >= 0),
  created_at timestamptz not null default now()
);

create index product_files_product_idx on public.product_files(product_id);

alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.product_media enable row level security;
alter table public.product_files enable row level security;

create policy "public reads product categories" on public.product_categories for select to anon, authenticated using (true);
create policy "public reads published products" on public.products for select to anon, authenticated using (status = 'published');
create policy "public reads published product media" on public.product_media for select to anon, authenticated using (exists (select 1 from public.products where products.id = product_id and products.status = 'published'));
-- product_files intentionally has NO select policy for anon/authenticated: purchasable files are never
-- listed or read directly from the table by public clients, only resolved server-side after a paid order.
revoke all on public.product_files from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.product_categories, public.products, public.product_media to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Private bucket for purchasable 3D files and payment screenshots. Never public.
insert into storage.buckets (id, name, public, file_size_limit)
values ('product-downloads', 'product-downloads', false, 524288000)
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit;

-- Admin read: everything, including drafts and private file lists.
create or replace function public.dashboard_store_content(p_token text)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  return jsonb_build_object(
    'categories', coalesce((select jsonb_agg(to_jsonb(x) order by x."order") from (select * from public.product_categories) x), '[]'::jsonb),
    'products', coalesce((select jsonb_agg(to_jsonb(x) order by x."order") from (select * from public.products) x), '[]'::jsonb)
  );
end $$;

create or replace function public.dashboard_store_product(p_token text, p_id bigint)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare result jsonb;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  select to_jsonb(p) || jsonb_build_object(
    'media', coalesce((select jsonb_agg(to_jsonb(m) order by m."order") from public.product_media m where m.product_id = p.id), '[]'::jsonb),
    'files', coalesce((select jsonb_agg(to_jsonb(f) order by f."order") from public.product_files f where f.product_id = p.id), '[]'::jsonb)
  )
  into result from public.products p where p.id = p_id;
  return result;
end $$;

create or replace function public.dashboard_upsert_product_category(p_token text, p_id bigint, p_name text, p_order integer)
returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_id is null then
    insert into public.product_categories (name, slug, "order")
    values (left(trim(p_name), 80), left(regexp_replace(lower(trim(p_name)), '[^a-z0-9]+', '-', 'g'), 90), coalesce(p_order, 0))
    returning id into result_id;
  else
    update public.product_categories set name = left(trim(p_name), 80), "order" = coalesce(p_order, 0) where id = p_id;
    result_id := p_id;
  end if;
  return result_id;
end $$;

create or replace function public.dashboard_delete_product_category(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.product_categories where id = p_id;
  return found;
end $$;

create or replace function public.dashboard_upsert_product(
  p_token text, p_id bigint, p_category_id bigint, p_title text, p_slug text,
  p_short_description text, p_description text, p_price_usd numeric, p_price_khr numeric,
  p_tags text, p_software text, p_file_formats text, p_polygon_count text, p_texture_info text,
  p_dimensions text, p_file_size text, p_version text, p_license text, p_compatibility text,
  p_requirements text, p_notes text, p_cover_image text, p_preview_video text, p_viewer_model text,
  p_is_featured boolean, p_status text, p_order integer
) returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_status not in ('draft', 'published') then raise exception 'invalid_status'; end if;
  if p_id is null then
    insert into public.products (
      category_id, title, slug, short_description, description, price_usd, price_khr, tags, software,
      file_formats, polygon_count, texture_info, dimensions, file_size, version, license, compatibility,
      requirements, notes, cover_image, preview_video, viewer_model, is_featured, status, "order"
    ) values (
      p_category_id, left(trim(p_title), 180), left(trim(p_slug), 200), left(coalesce(p_short_description, ''), 420),
      coalesce(p_description, ''), coalesce(p_price_usd, 0), coalesce(p_price_khr, 0), coalesce(p_tags, ''),
      coalesce(p_software, ''), coalesce(p_file_formats, ''), left(coalesce(p_polygon_count, ''), 40),
      coalesce(p_texture_info, ''), left(coalesce(p_dimensions, ''), 120), left(coalesce(p_file_size, ''), 40),
      left(coalesce(p_version, ''), 40), coalesce(p_license, ''), coalesce(p_compatibility, ''),
      coalesce(p_requirements, ''), coalesce(p_notes, ''), coalesce(p_cover_image, ''), coalesce(p_preview_video, ''),
      coalesce(p_viewer_model, ''), coalesce(p_is_featured, false), p_status, coalesce(p_order, 0)
    ) returning id into result_id;
  else
    update public.products set
      category_id = p_category_id, title = left(trim(p_title), 180), slug = left(trim(p_slug), 200),
      short_description = left(coalesce(p_short_description, ''), 420), description = coalesce(p_description, ''),
      price_usd = coalesce(p_price_usd, 0), price_khr = coalesce(p_price_khr, 0), tags = coalesce(p_tags, ''),
      software = coalesce(p_software, ''), file_formats = coalesce(p_file_formats, ''),
      polygon_count = left(coalesce(p_polygon_count, ''), 40), texture_info = coalesce(p_texture_info, ''),
      dimensions = left(coalesce(p_dimensions, ''), 120), file_size = left(coalesce(p_file_size, ''), 40),
      version = left(coalesce(p_version, ''), 40), license = coalesce(p_license, ''),
      compatibility = coalesce(p_compatibility, ''), requirements = coalesce(p_requirements, ''),
      notes = coalesce(p_notes, ''), cover_image = coalesce(p_cover_image, ''),
      preview_video = coalesce(p_preview_video, ''), viewer_model = coalesce(p_viewer_model, ''),
      is_featured = coalesce(p_is_featured, false), status = p_status, "order" = coalesce(p_order, 0),
      updated_at = now()
    where id = p_id;
    result_id := p_id;
  end if;
  return result_id;
end $$;

create or replace function public.dashboard_delete_product(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.products where id = p_id;
  return found;
end $$;

create or replace function public.dashboard_add_product_media(p_token text, p_product_id bigint, p_media_type text, p_file_path text, p_caption text, p_order integer)
returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_media_type not in ('image', 'video') then raise exception 'invalid_media_type'; end if;
  insert into public.product_media (product_id, media_type, file_path, caption, "order")
  values (p_product_id, p_media_type, p_file_path, left(coalesce(p_caption, ''), 220), coalesce(p_order, 0))
  returning id into result_id;
  return result_id;
end $$;

create or replace function public.dashboard_delete_product_media(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.product_media where id = p_id;
  return found;
end $$;

create or replace function public.dashboard_add_product_file(p_token text, p_product_id bigint, p_file_name text, p_file_path text, p_file_size bigint, p_order integer)
returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  insert into public.product_files (product_id, file_name, file_path, file_size, "order")
  values (p_product_id, left(p_file_name, 255), p_file_path, p_file_size, coalesce(p_order, 0))
  returning id into result_id;
  return result_id;
end $$;

create or replace function public.dashboard_delete_product_file(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.product_files where id = p_id;
  return found;
end $$;

do $$
declare fn text;
begin
  foreach fn in array array[
    'dashboard_store_content(text)',
    'dashboard_store_product(text,bigint)',
    'dashboard_upsert_product_category(text,bigint,text,integer)',
    'dashboard_delete_product_category(text,bigint)',
    'dashboard_upsert_product(text,bigint,bigint,text,text,text,text,numeric,numeric,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,boolean,text,integer)',
    'dashboard_delete_product(text,bigint)',
    'dashboard_add_product_media(text,bigint,text,text,text,integer)',
    'dashboard_delete_product_media(text,bigint)',
    'dashboard_add_product_file(text,bigint,text,text,bigint,integer)',
    'dashboard_delete_product_file(text,bigint)'
  ] loop
    execute format('revoke execute on function public.%s from public, authenticated, service_role', fn);
    execute format('grant execute on function public.%s to anon', fn);
  end loop;
end $$;
