-- Wishlist/favorites for the 3D store. Same trusted-session pattern as orders/inquiries:
-- the customer_id passed to these RPCs is never taken at face value from an untrusted
-- caller — every route that invokes them first reads it from a verified session cookie
-- server-side, so a toggle/list call can only ever act on the caller's own wishlist.

create table public.wishlist_items (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (customer_id, product_id)
);

create index wishlist_items_customer_idx on public.wishlist_items(customer_id);

alter table public.wishlist_items enable row level security;
revoke all on public.wishlist_items from anon, authenticated;

create or replace function public.toggle_wishlist_item(p_customer_id bigint, p_product_id bigint)
returns boolean -- true if now wishlisted, false if removed
language plpgsql security definer set search_path = public
as $$
declare removed_count int;
begin
  delete from public.wishlist_items where customer_id = p_customer_id and product_id = p_product_id;
  get diagnostics removed_count = row_count;
  if removed_count > 0 then return false; end if;
  insert into public.wishlist_items (customer_id, product_id) values (p_customer_id, p_product_id);
  return true;
end $$;

create or replace function public.get_customer_wishlist_ids(p_customer_id bigint)
returns bigint[] language sql stable security definer set search_path = public
as $$ select coalesce(array_agg(product_id), array[]::bigint[]) from public.wishlist_items where customer_id = p_customer_id $$;

create or replace function public.get_customer_wishlist(p_customer_id bigint)
returns jsonb language plpgsql stable security definer set search_path = public
as $$
begin
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', p.id, 'slug', p.slug, 'title', p.title, 'short_description', p.short_description,
      'price_usd', p.price_usd, 'price_khr', p.price_khr, 'cover_image', p.cover_image,
      'file_formats', p.file_formats, 'is_featured', p.is_featured, 'status', p.status,
      'added_at', w.created_at
    ) order by w.created_at desc)
    from public.wishlist_items w join public.products p on p.id = w.product_id
    where w.customer_id = p_customer_id
  ), '[]'::jsonb);
end $$;

grant execute on function public.toggle_wishlist_item(bigint, bigint) to anon, authenticated;
grant execute on function public.get_customer_wishlist_ids(bigint) to anon, authenticated;
grant execute on function public.get_customer_wishlist(bigint) to anon, authenticated;
