-- Customer accounts for the 3D Store. Orders can now belong to a registered
-- customer (visible anytime in "My Account") or remain guest orders reachable
-- only by their access_token link, exactly as before. Both keep working.
--
-- Passwords are hashed with pgcrypto's bcrypt (crypt/gen_salt) entirely inside
-- Postgres. No function ever returns a password hash over the wire — login
-- verification happens inside the database and only a boolean-shaped result
-- (success + profile, or nothing) ever leaves it.

create table public.customers (
  id bigint generated by default as identity primary key,
  email varchar(254) not null unique,
  password_hash text not null,
  full_name varchar(120) not null,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists customer_id bigint references public.customers(id) on delete set null;
create index if not exists orders_customer_idx on public.orders(customer_id);

create table public.customer_login_attempts (
  id bigint generated by default as identity primary key,
  ip_address inet not null,
  created_at timestamptz not null default now()
);
create index customer_login_attempts_ip_created_idx on public.customer_login_attempts(ip_address, created_at desc);

alter table public.customers enable row level security;
alter table public.customer_login_attempts enable row level security;
revoke all on public.customers from anon, authenticated;
revoke all on public.customer_login_attempts from anon, authenticated;

create or replace function public.register_customer(p_email text, p_password text, p_full_name text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare new_id bigint;
begin
  if p_password is null or char_length(p_password) < 8 then raise exception 'weak_password'; end if;
  if exists (select 1 from public.customers where lower(email) = lower(trim(p_email))) then
    raise exception 'email_taken';
  end if;
  insert into public.customers (email, password_hash, full_name)
  values (lower(trim(p_email)), extensions.crypt(p_password, extensions.gen_salt('bf')), left(trim(p_full_name), 120))
  returning id into new_id;
  return jsonb_build_object('id', new_id, 'email', lower(trim(p_email)), 'full_name', left(trim(p_full_name), 120));
end $$;

create or replace function public.verify_customer_login(p_email text, p_password text, p_ip_address inet)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare result jsonb;
begin
  delete from public.customer_login_attempts where created_at < now() - interval '1 day';
  if p_ip_address is not null and (
    select count(*) from public.customer_login_attempts
    where ip_address = p_ip_address and created_at > now() - interval '15 minutes'
  ) >= 8 then
    raise exception 'rate_limited';
  end if;
  if p_ip_address is not null then
    insert into public.customer_login_attempts (ip_address) values (p_ip_address);
  end if;

  select jsonb_build_object('id', id, 'email', email, 'full_name', full_name)
  into result
  from public.customers
  where lower(email) = lower(trim(p_email))
    and password_hash = extensions.crypt(p_password, password_hash);

  return result;
end $$;

-- A customer's own orders + product info, scoped strictly to their id.
create or replace function public.get_customer_orders(p_customer_id bigint)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', o.id, 'order_number', o.order_number, 'access_token', o.access_token,
      'status', o.status, 'price_usd', o.price_usd, 'price_khr', o.price_khr,
      'created_at', o.created_at, 'admin_notes', case when o.status = 'rejected' then o.admin_notes else '' end,
      'product', jsonb_build_object('id', p.id, 'title', p.title, 'slug', p.slug, 'cover_image', p.cover_image)
    ) order by o.created_at desc)
    from public.orders o join public.products p on p.id = o.product_id
    where o.customer_id = p_customer_id
  ), '[]'::jsonb);
end $$;

-- Attach a customer to the order they're placing (called right after submit_order
-- when the buyer is logged in). Only fills a currently-unset customer_id.
create or replace function public.attach_order_customer(p_order_id bigint, p_customer_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  update public.orders set customer_id = p_customer_id where id = p_order_id and customer_id is null;
  return found;
end $$;

do $$
declare fn text;
begin
  foreach fn in array array[
    'register_customer(text,text,text)',
    'verify_customer_login(text,text,inet)',
    'get_customer_orders(bigint)',
    'attach_order_customer(bigint,bigint)'
  ] loop
    execute format('revoke execute on function public.%s from public, authenticated, service_role', fn);
    execute format('grant execute on function public.%s to anon', fn);
  end loop;
end $$;
