-- Rate-limit the admin login route (previously unlimited, unlike submit_inquiry)
-- and stop keeping visitor/inquiry IP addresses indefinitely.

create table public.admin_login_attempts (
  id bigint generated by default as identity primary key,
  ip_address inet not null,
  created_at timestamptz not null default now()
);

create index admin_login_attempts_ip_created_idx
on public.admin_login_attempts(ip_address, created_at desc);

alter table public.admin_login_attempts enable row level security;
revoke all on public.admin_login_attempts from anon, authenticated;

-- Records an attempt and raises 'rate_limited' once an IP has tried too often
-- in the last 15 minutes. Self-purges attempts older than a day so the table
-- never needs a separate cron job to stay small.
create or replace function public.check_login_rate_limit(p_ip inet)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.admin_login_attempts where created_at < now() - interval '1 day';

  if p_ip is not null and (
    select count(*)
    from public.admin_login_attempts
    where ip_address = p_ip
      and created_at > now() - interval '15 minutes'
  ) >= 8 then
    raise exception 'rate_limited';
  end if;

  if p_ip is not null then
    insert into public.admin_login_attempts (ip_address) values (p_ip);
  end if;

  return true;
end
$$;

revoke execute on function public.check_login_rate_limit(inet)
from public, authenticated, service_role;
grant execute on function public.check_login_rate_limit(inet) to anon;

-- Nulls out ip_address on rows old enough that the only remaining reason to
-- keep it (abuse detection / rate limiting) no longer applies.
create or replace function private.purge_expired_ip_addresses()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.project_inquiries
  set ip_address = null
  where ip_address is not null
    and created_at < now() - interval '90 days';

  update public.visitor_events
  set ip_address = null
  where ip_address is not null
    and created_at < now() - interval '90 days';
end
$$;

revoke execute on function private.purge_expired_ip_addresses()
from public, anon, authenticated, service_role;

-- Re-create dashboard_snapshot to purge expired IPs on every admin load.
-- No longer STABLE: it now has a (deliberate, internal) side effect.
create or replace function public.dashboard_snapshot(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.dashboard_token_ok(p_token) then
    raise exception 'unauthorized';
  end if;

  perform private.purge_expired_ip_addresses();

  return jsonb_build_object(
    'total_visits', (select count(*) from public.visitor_events),
    'today_visits', (
      select count(*)
      from public.visitor_events
      where created_at::date = (now() at time zone 'Asia/Phnom_Penh')::date
    ),
    'unique_visitors', (select count(distinct session_key) from public.visitor_events),
    'new_inquiries', (select count(*) from public.project_inquiries where status = 'new'),
    'accepted_projects', (select count(*) from public.project_inquiries where status = 'accepted'),
    'latest_visits', coalesce((
      select jsonb_agg(to_jsonb(v))
      from (
        select id, path, referrer, device_type, device_model, device_vendor,
          browser, browser_version, os, os_version, platform, language, timezone,
          screen_width, screen_height, viewport_width, viewport_height,
          connection_type, cpu_cores, device_memory, touch_support, is_bot,
          city, region, country, country_code, created_at
        from public.visitor_events
        order by created_at desc
        limit 50
      ) v
    ), '[]'::jsonb),
    'latest_inquiries', coalesce((
      select jsonb_agg(to_jsonb(i))
      from (
        select id, full_name, email, phone_or_telegram, company, service_needed,
          estimated_budget, preferred_timeline, project_description, attachment,
          consent, status, admin_notes, client_response, last_notification_status,
          last_notified_at, is_reviewed, created_at, updated_at
        from public.project_inquiries
        order by created_at desc
        limit 20
      ) i
    ), '[]'::jsonb),
    'device_breakdown', coalesce((
      select jsonb_agg(to_jsonb(d))
      from (
        select device_type, count(*)::integer as total
        from public.visitor_events
        group by device_type
        order by total desc
      ) d
    ), '[]'::jsonb),
    'model_breakdown', coalesce((
      select jsonb_agg(to_jsonb(m))
      from (
        select coalesce(nullif(device_model, ''), 'Unknown') as device_model,
          coalesce(nullif(device_vendor, ''), 'Unknown') as device_vendor,
          count(*)::integer as total
        from public.visitor_events
        group by 1, 2
        order by total desc
        limit 10
      ) m
    ), '[]'::jsonb),
    'location_breakdown', coalesce((
      select jsonb_agg(to_jsonb(l))
      from (
        select coalesce(nullif(city, ''), 'Unknown city') as city,
          coalesce(nullif(region, ''), 'Unknown region') as region,
          coalesce(nullif(country, ''), nullif(country_code, ''), 'Unknown country') as country,
          count(*)::integer as total
        from public.visitor_events
        group by 1, 2, 3
        order by total desc
        limit 10
      ) l
    ), '[]'::jsonb),
    'top_pages', coalesce((
      select jsonb_agg(to_jsonb(p))
      from (
        select path, count(*)::integer as total
        from public.visitor_events
        group by path
        order by total desc
        limit 8
      ) p
    ), '[]'::jsonb)
  );
end
$$;

revoke execute on function public.dashboard_snapshot(text) from public, authenticated, service_role;
grant execute on function public.dashboard_snapshot(text) to anon;
