-- Manual-payment checkout: orders, admin review, and a small payment-settings
-- extension to site_settings for the ABA QR image + account info text.

alter table public.site_settings
  add column if not exists aba_qr_image text not null default '',
  add column if not exists aba_account_info text not null default '';

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number varchar(30) not null unique,
  access_token uuid not null default gen_random_uuid() unique,
  product_id bigint not null references public.products(id) on delete restrict,
  customer_name varchar(120) not null,
  customer_email varchar(254) not null,
  customer_phone varchar(80) not null default '',
  price_usd numeric(10,2) not null,
  price_khr numeric(12,0) not null,
  payment_reference varchar(160) not null default '',
  payment_screenshot text not null default '',
  status varchar(24) not null default 'pending_payment' check (status in (
    'pending_payment', 'payment_submitted', 'under_review', 'paid', 'rejected', 'completed'
  )),
  admin_notes varchar(500) not null default '',
  ip_address inet,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index orders_status_created_idx on public.orders(status, created_at desc);
create index orders_product_idx on public.orders(product_id);
create index orders_access_token_idx on public.orders(access_token);

create table public.order_messages (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  message_type varchar(24) not null check (message_type in ('created', 'submitted', 'approved', 'rejected')),
  subject varchar(220) not null default '',
  body text not null default '',
  delivery_status varchar(20) not null check (delivery_status in ('sent', 'not-configured', 'not-applicable', 'failed')),
  created_at timestamptz not null default now()
);

create index order_messages_order_created_idx on public.order_messages(order_id, created_at desc);

alter table public.orders enable row level security;
alter table public.order_messages enable row level security;
revoke all on public.orders from anon, authenticated;
revoke all on public.order_messages from anon, authenticated;

-- Customer-facing: create an order (rate-limited), fetch it back by its own
-- access token, and submit payment proof. All security-definer, all scoped
-- to a single order the caller already knows the token for.

create or replace function public.submit_order(p_product_id bigint, p_customer_name text, p_customer_email text, p_customer_phone text, p_ip_address inet)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  new_id bigint;
  new_number text;
  new_token uuid;
  product_row public.products%rowtype;
begin
  if p_ip_address is not null and exists (
    select 1 from public.orders where ip_address = p_ip_address and created_at > now() - interval '5 minutes'
  ) then
    raise exception 'rate_limited';
  end if;

  select * into product_row from public.products where id = p_product_id and status = 'published';
  if not found then raise exception 'product_not_found'; end if;

  -- Insert first so the row's own identity value can be used to build a
  -- matching order number, instead of pre-consuming the sequence separately
  -- (which would desync the number from the actual id).
  insert into public.orders (order_number, product_id, customer_name, customer_email, customer_phone, price_usd, price_khr, ip_address)
  values ('PENDING', p_product_id, left(trim(p_customer_name), 120), left(trim(p_customer_email), 254), left(trim(coalesce(p_customer_phone, '')), 80), product_row.price_usd, product_row.price_khr, p_ip_address)
  returning id, access_token into new_id, new_token;

  new_number := 'ORD-' || to_char(now(), 'YYYY') || '-' || lpad(new_id::text, 6, '0');
  update public.orders set order_number = new_number where id = new_id;

  return jsonb_build_object('id', new_id, 'order_number', new_number, 'access_token', new_token);
end $$;

create or replace function public.get_order_by_token(p_access_token uuid)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare result jsonb;
begin
  select jsonb_build_object(
    'id', o.id, 'order_number', o.order_number, 'status', o.status,
    'customer_name', o.customer_name, 'customer_email', o.customer_email,
    'price_usd', o.price_usd, 'price_khr', o.price_khr, 'created_at', o.created_at,
    'reviewed_at', o.reviewed_at, 'admin_notes', case when o.status = 'rejected' then o.admin_notes else '' end,
    'product', jsonb_build_object('id', p.id, 'title', p.title, 'slug', p.slug, 'cover_image', p.cover_image)
  ) into result
  from public.orders o join public.products p on p.id = o.product_id
  where o.access_token = p_access_token;
  return result;
end $$;

create or replace function public.submit_order_payment(p_access_token uuid, p_payment_reference text, p_payment_screenshot text)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  update public.orders
  set payment_reference = left(trim(coalesce(p_payment_reference, '')), 160),
      payment_screenshot = coalesce(p_payment_screenshot, ''),
      status = 'payment_submitted',
      updated_at = now()
  where access_token = p_access_token and status = 'pending_payment';
  return found;
end $$;

-- Admin: list/review orders, and resolve the actual private download links
-- only for an order that is genuinely paid/completed.

create or replace function public.dashboard_store_orders(p_token text)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  return coalesce((
    select jsonb_agg(to_jsonb(o) - 'access_token' || jsonb_build_object('product_title', p.title) order by o.created_at desc)
    from public.orders o join public.products p on p.id = o.product_id
  ), '[]'::jsonb);
end $$;

create or replace function public.dashboard_store_order(p_token text, p_id bigint)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare result jsonb;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  select to_jsonb(o) || jsonb_build_object(
    'product', to_jsonb(p),
    'messages', coalesce((select jsonb_agg(to_jsonb(m) order by m.created_at desc) from public.order_messages m where m.order_id = o.id), '[]'::jsonb)
  ) into result
  from public.orders o join public.products p on p.id = o.product_id
  where o.id = p_id;
  return result;
end $$;

create or replace function public.dashboard_review_order(p_token text, p_id bigint, p_decision text, p_admin_notes text)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_decision not in ('approve', 'reject') then raise exception 'invalid_decision'; end if;
  update public.orders set
    status = case when p_decision = 'approve' then 'paid' else 'rejected' end,
    admin_notes = left(coalesce(p_admin_notes, ''), 500),
    reviewed_at = now(),
    updated_at = now()
  where id = p_id and status in ('payment_submitted', 'under_review');
  return found;
end $$;

create or replace function public.dashboard_record_order_message(p_token text, p_id bigint, p_message_type text, p_subject text, p_body text, p_delivery_status text)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  insert into public.order_messages (order_id, message_type, subject, body, delivery_status)
  values (p_id, p_message_type, left(coalesce(p_subject, ''), 220), coalesce(p_body, ''), p_delivery_status);
  return true;
end $$;

do $$
declare fn text;
begin
  foreach fn in array array[
    'submit_order(bigint,text,text,text,inet)',
    'get_order_by_token(uuid)',
    'submit_order_payment(uuid,text,text)',
    'dashboard_store_orders(text)',
    'dashboard_store_order(text,bigint)',
    'dashboard_review_order(text,bigint,text,text)',
    'dashboard_record_order_message(text,bigint,text,text,text,text)'
  ] loop
    execute format('revoke execute on function public.%s from public, authenticated, service_role', fn);
    execute format('grant execute on function public.%s to anon', fn);
  end loop;
end $$;
