-- Move Services / Skills / Software from hardcoded lib/content.ts arrays into
-- the database, seeded verbatim from the current hardcoded copy, so admins
-- can edit site content without touching code.

create table public.services (
  id bigint generated by default as identity primary key,
  title varchar(160) not null unique,
  description text not null default '',
  "order" integer not null default 0 check ("order" >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.skill_groups (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  "order" integer not null default 0 check ("order" >= 0)
);

create table public.skills (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.skill_groups(id) on delete cascade,
  name varchar(80) not null,
  "order" integer not null default 0 check ("order" >= 0)
);

create index skills_group_order_idx on public.skills(group_id, "order");

create table public.software_tools (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  "order" integer not null default 0 check ("order" >= 0)
);

alter table public.services enable row level security;
alter table public.skill_groups enable row level security;
alter table public.skills enable row level security;
alter table public.software_tools enable row level security;

create policy "public reads active services" on public.services for select to anon, authenticated using (is_active);
create policy "public reads skill groups" on public.skill_groups for select to anon, authenticated using (true);
create policy "public reads skills" on public.skills for select to anon, authenticated using (true);
create policy "public reads software tools" on public.software_tools for select to anon, authenticated using (true);

grant select on public.services, public.skill_groups, public.skills, public.software_tools to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.services (title, description, "order") values
('Graphic Design', 'Visual materials for brands, campaigns, social media, presentations, print, and digital communication.', 0),
('Poster Design', 'Campaign posters, product posters, food and beverage promotions, event visuals, and social-ready artwork designed for clear recognition.', 1),
('Video Editing', 'Professional editing, pacing, transitions, color correction, sound cleanup, subtitles, motion graphics, and delivery for different platforms.', 2),
('Videography and Filmmaking', 'Creative planning, shot lists, camera operation, interviews, company videos, events, promotional videos, and cinematic storytelling.', 3),
('Photography', 'Product, portrait, event, lifestyle, commercial, and corporate photography with professional post-production.', 4),
('3D Modeling and Visualization', '3D products, environments, architectural scenes, visual concepts, lighting, materials, and rendering.', 5),
('3D Animation', 'Camera animation, product animation, environment animation, motion studies, and visual storytelling.', 6),
('Social Media Content', 'Short-form videos, reels, TikTok content, promotional visuals, campaign content, and platform-ready exports.', 7),
('Creative Consultation', 'Support with visual direction, content planning, concepts, storyboards, campaign ideas, and production workflows.', 8);

insert into public.skill_groups (name, "order") values
('Creative Design', 0),
('Video Production', 1),
('3D Production', 2),
('Photography', 3),
('Filmmaking and Videography', 4);

insert into public.skills (group_id, name, "order")
select g.id, s.name, s.ord
from public.skill_groups g
join (values
  ('Creative Design', 'Graphic Design', 0), ('Creative Design', 'Brand Visuals', 1), ('Creative Design', 'Social Media Design', 2),
  ('Creative Design', 'Poster Design', 3), ('Creative Design', 'Print Design', 4), ('Creative Design', 'Layout Design', 5),
  ('Creative Design', 'Marketing Materials', 6),
  ('Video Production', 'Video Editing', 0), ('Video Production', 'Color Correction', 1), ('Video Production', 'Color Grading', 2),
  ('Video Production', 'Motion Graphics', 3), ('Video Production', 'Audio Cleanup', 4), ('Video Production', 'Social Media Video', 5),
  ('Video Production', 'Promotional Video', 6), ('Video Production', 'Cinematic Editing', 7),
  ('3D Production', '3D Modeling', 0), ('3D Production', '3D Environment Design', 1), ('3D Production', 'Product Visualization', 2),
  ('3D Production', 'Architectural Visualization', 3), ('3D Production', 'Lighting', 4), ('3D Production', 'Rendering', 5),
  ('3D Production', '3D Animation', 6), ('3D Production', 'Camera Animation', 7),
  ('Photography', 'Commercial Photography', 0), ('Photography', 'Product Photography', 1), ('Photography', 'Portrait Photography', 2),
  ('Photography', 'Event Photography', 3), ('Photography', 'Lifestyle Photography', 4), ('Photography', 'Photo Editing', 5),
  ('Photography', 'Photo Retouching', 6),
  ('Filmmaking and Videography', 'Creative Direction', 0), ('Filmmaking and Videography', 'Storyboarding', 1),
  ('Filmmaking and Videography', 'Shot Planning', 2), ('Filmmaking and Videography', 'Camera Operation', 3),
  ('Filmmaking and Videography', 'Cinematography', 4), ('Filmmaking and Videography', 'Interview Production', 5),
  ('Filmmaking and Videography', 'Behind-the-Scenes Coverage', 6), ('Filmmaking and Videography', 'Short-Form Content Production', 7)
) as s(group_name, name, ord) on s.group_name = g.name;

insert into public.software_tools (name, "order") values
('Photoshop', 0), ('Illustrator', 1), ('After Effects', 2), ('Premiere Pro', 3),
('DaVinci Resolve', 4), ('Blender', 5), ('CapCut', 6), ('CorelDRAW', 7);

-- Admin read: everything, including inactive services, gated by the same
-- dashboard token pattern as dashboard_snapshot.
create or replace function public.dashboard_content(p_token text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.dashboard_token_ok(p_token) then
    raise exception 'unauthorized';
  end if;

  return jsonb_build_object(
    'site_settings', (select to_jsonb(s) from public.site_settings s order by id limit 1),
    'services', coalesce((select jsonb_agg(to_jsonb(x) order by x."order") from (select * from public.services) x), '[]'::jsonb),
    'skill_groups', coalesce((select jsonb_agg(to_jsonb(x) order by x."order") from (select * from public.skill_groups) x), '[]'::jsonb),
    'skills', coalesce((select jsonb_agg(to_jsonb(x) order by x."order") from (select * from public.skills) x), '[]'::jsonb),
    'software_tools', coalesce((select jsonb_agg(to_jsonb(x) order by x."order") from (select * from public.software_tools) x), '[]'::jsonb)
  );
end
$$;

create or replace function public.dashboard_update_site_settings(
  p_token text, p_professional_title text, p_hero_intro text, p_khmer_intro text,
  p_professional_intro text, p_email text, p_phone text, p_location text,
  p_showreel_title text, p_youtube_url text, p_vimeo_url text, p_local_video_url text
) returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  update public.site_settings set
    professional_title = left(trim(coalesce(p_professional_title, '')), 160),
    hero_intro = coalesce(p_hero_intro, ''),
    khmer_intro = left(coalesce(p_khmer_intro, ''), 255),
    professional_intro = coalesce(p_professional_intro, ''),
    email = left(trim(coalesce(p_email, '')), 254),
    phone = left(trim(coalesce(p_phone, '')), 40),
    location = left(trim(coalesce(p_location, '')), 120),
    showreel_title = left(trim(coalesce(p_showreel_title, '')), 160),
    youtube_url = coalesce(p_youtube_url, ''),
    vimeo_url = coalesce(p_vimeo_url, ''),
    local_video_url = coalesce(p_local_video_url, ''),
    updated_at = now()
  where id = (select id from public.site_settings order by id limit 1);
  return found;
end $$;

create or replace function public.dashboard_upsert_service(
  p_token text, p_id bigint, p_title text, p_description text, p_order integer, p_is_active boolean
) returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_id is null then
    insert into public.services (title, description, "order", is_active)
    values (left(trim(p_title), 160), coalesce(p_description, ''), coalesce(p_order, 0), coalesce(p_is_active, true))
    returning id into result_id;
  else
    update public.services set
      title = left(trim(p_title), 160), description = coalesce(p_description, ''),
      "order" = coalesce(p_order, 0), is_active = coalesce(p_is_active, true), updated_at = now()
    where id = p_id;
    result_id := p_id;
  end if;
  return result_id;
end $$;

create or replace function public.dashboard_delete_service(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.services where id = p_id;
  return found;
end $$;

create or replace function public.dashboard_upsert_skill_group(p_token text, p_id bigint, p_name text, p_order integer)
returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_id is null then
    insert into public.skill_groups (name, "order") values (left(trim(p_name), 80), coalesce(p_order, 0)) returning id into result_id;
  else
    update public.skill_groups set name = left(trim(p_name), 80), "order" = coalesce(p_order, 0) where id = p_id;
    result_id := p_id;
  end if;
  return result_id;
end $$;

create or replace function public.dashboard_delete_skill_group(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.skill_groups where id = p_id;
  return found;
end $$;

create or replace function public.dashboard_upsert_skill(p_token text, p_id bigint, p_group_id bigint, p_name text, p_order integer)
returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_id is null then
    insert into public.skills (group_id, name, "order") values (p_group_id, left(trim(p_name), 80), coalesce(p_order, 0)) returning id into result_id;
  else
    update public.skills set group_id = coalesce(p_group_id, group_id), name = left(trim(p_name), 80), "order" = coalesce(p_order, 0) where id = p_id;
    result_id := p_id;
  end if;
  return result_id;
end $$;

create or replace function public.dashboard_delete_skill(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.skills where id = p_id;
  return found;
end $$;

create or replace function public.dashboard_upsert_software(p_token text, p_id bigint, p_name text, p_order integer)
returns bigint language plpgsql security definer set search_path = '' as $$
declare result_id bigint;
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  if p_id is null then
    insert into public.software_tools (name, "order") values (left(trim(p_name), 80), coalesce(p_order, 0)) returning id into result_id;
  else
    update public.software_tools set name = left(trim(p_name), 80), "order" = coalesce(p_order, 0) where id = p_id;
    result_id := p_id;
  end if;
  return result_id;
end $$;

create or replace function public.dashboard_delete_software(p_token text, p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not private.dashboard_token_ok(p_token) then raise exception 'unauthorized'; end if;
  delete from public.software_tools where id = p_id;
  return found;
end $$;

revoke execute on function public.dashboard_content(text) from public, authenticated, service_role;
revoke execute on function public.dashboard_update_site_settings(text,text,text,text,text,text,text,text,text,text,text,text) from public, authenticated, service_role;
revoke execute on function public.dashboard_upsert_service(text,bigint,text,text,integer,boolean) from public, authenticated, service_role;
revoke execute on function public.dashboard_delete_service(text,bigint) from public, authenticated, service_role;
revoke execute on function public.dashboard_upsert_skill_group(text,bigint,text,integer) from public, authenticated, service_role;
revoke execute on function public.dashboard_delete_skill_group(text,bigint) from public, authenticated, service_role;
revoke execute on function public.dashboard_upsert_skill(text,bigint,bigint,text,integer) from public, authenticated, service_role;
revoke execute on function public.dashboard_delete_skill(text,bigint) from public, authenticated, service_role;
revoke execute on function public.dashboard_upsert_software(text,bigint,text,integer) from public, authenticated, service_role;
revoke execute on function public.dashboard_delete_software(text,bigint) from public, authenticated, service_role;

grant execute on function public.dashboard_content(text) to anon;
grant execute on function public.dashboard_update_site_settings(text,text,text,text,text,text,text,text,text,text,text,text) to anon;
grant execute on function public.dashboard_upsert_service(text,bigint,text,text,integer,boolean) to anon;
grant execute on function public.dashboard_delete_service(text,bigint) to anon;
grant execute on function public.dashboard_upsert_skill_group(text,bigint,text,integer) to anon;
grant execute on function public.dashboard_delete_skill_group(text,bigint) to anon;
grant execute on function public.dashboard_upsert_skill(text,bigint,bigint,text,integer) to anon;
grant execute on function public.dashboard_delete_skill(text,bigint) to anon;
grant execute on function public.dashboard_upsert_software(text,bigint,text,integer) to anon;
grant execute on function public.dashboard_delete_software(text,bigint) to anon;
