alter table public.project_inquiries
  add column if not exists client_response text not null default '',
  add column if not exists last_notification_status varchar(20) not null default '',
  add column if not exists last_notified_at timestamptz;

alter table public.project_inquiries
  drop constraint if exists project_inquiries_last_notification_status_check;

alter table public.project_inquiries
  add constraint project_inquiries_last_notification_status_check
  check (last_notification_status in ('', 'sent', 'not-configured', 'not-applicable', 'failed'));

create table if not exists public.inquiry_messages (
  id bigint generated by default as identity primary key,
  inquiry_id bigint not null references public.project_inquiries(id) on delete cascade,
  message_type varchar(24) not null check (message_type in ('receipt', 'accepted', 'declined', 'reply', 'status')),
  subject varchar(220) not null default '',
  body text not null default '',
  delivery_status varchar(20) not null check (delivery_status in ('sent', 'not-configured', 'not-applicable', 'failed')),
  created_at timestamptz not null default now()
);

create index if not exists inquiry_messages_inquiry_created_idx
on public.inquiry_messages(inquiry_id, created_at desc);

alter table public.inquiry_messages enable row level security;
revoke all on public.inquiry_messages from anon, authenticated;

alter table public.visitor_events
  add column if not exists city varchar(120) not null default '',
  add column if not exists region varchar(120) not null default '',
  add column if not exists country varchar(120) not null default '',
  add column if not exists country_code varchar(8) not null default '',
  add column if not exists device_vendor varchar(80) not null default '',
  add column if not exists browser_version varchar(40) not null default '',
  add column if not exists os_version varchar(60) not null default '',
  add column if not exists connection_type varchar(24) not null default '',
  add column if not exists cpu_cores smallint,
  add column if not exists device_memory numeric(6,2),
  add column if not exists touch_support boolean not null default false,
  add column if not exists is_bot boolean not null default false;

alter table public.visitor_events
  drop constraint if exists visitor_events_cpu_cores_check,
  drop constraint if exists visitor_events_device_memory_check;

alter table public.visitor_events
  add constraint visitor_events_cpu_cores_check check (cpu_cores is null or cpu_cores between 1 and 512),
  add constraint visitor_events_device_memory_check check (device_memory is null or device_memory between 0 and 1024);

create index if not exists visitor_events_location_idx
on public.visitor_events(country_code, region, city);

create index if not exists visitor_events_model_idx
on public.visitor_events(device_model) where device_model <> '' and device_model <> 'Unknown';

drop policy if exists "public records valid visits" on public.visitor_events;
create policy "public records valid visits"
on public.visitor_events
for insert
to anon
with check (
  char_length(session_key) between 1 and 80
  and char_length(path) between 1 and 255
  and path like '/%'
  and char_length(referrer) <= 1000
  and char_length(user_agent) <= 2000
  and char_length(device_type) <= 40
  and char_length(device_model) <= 120
  and char_length(device_vendor) <= 80
  and char_length(browser) <= 80
  and char_length(browser_version) <= 40
  and char_length(os) <= 80
  and char_length(os_version) <= 60
  and char_length(city) <= 120
  and char_length(region) <= 120
  and char_length(country) <= 120
  and char_length(country_code) <= 8
);

create or replace function public.dashboard_snapshot(p_token text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.dashboard_token_ok(p_token) then
    raise exception 'unauthorized';
  end if;

  return jsonb_build_object(
    'total_visits', (select count(*) from public.visitor_events),
    'today_visits', (
      select count(*)
      from public.visitor_events
      where created_at::date = (now() at time zone 'Asia/Phnom_Penh')::date
    ),
    'unique_visitors', (select count(distinct session_key) from public.visitor_events),
    'new_inquiries', (select count(*) from public.project_inquiries where status = 'new'),
    'accepted_projects', (select count(*) from public.project_inquiries where status = 'accepted'),
    'latest_visits', coalesce((
      select jsonb_agg(to_jsonb(v))
      from (
        select id, path, referrer, device_type, device_model, device_vendor,
          browser, browser_version, os, os_version, platform, language, timezone,
          screen_width, screen_height, viewport_width, viewport_height,
          connection_type, cpu_cores, device_memory, touch_support, is_bot,
          city, region, country, country_code, created_at
        from public.visitor_events
        order by created_at desc
        limit 50
      ) v
    ), '[]'::jsonb),
    'latest_inquiries', coalesce((
      select jsonb_agg(to_jsonb(i))
      from (
        select id, full_name, email, phone_or_telegram, company, service_needed,
          estimated_budget, preferred_timeline, project_description, attachment,
          consent, status, admin_notes, client_response, last_notification_status,
          last_notified_at, is_reviewed, created_at, updated_at
        from public.project_inquiries
        order by created_at desc
        limit 20
      ) i
    ), '[]'::jsonb),
    'device_breakdown', coalesce((
      select jsonb_agg(to_jsonb(d))
      from (
        select device_type, count(*)::integer as total
        from public.visitor_events
        group by device_type
        order by total desc
      ) d
    ), '[]'::jsonb),
    'model_breakdown', coalesce((
      select jsonb_agg(to_jsonb(m))
      from (
        select coalesce(nullif(device_model, ''), 'Unknown') as device_model,
          coalesce(nullif(device_vendor, ''), 'Unknown') as device_vendor,
          count(*)::integer as total
        from public.visitor_events
        group by 1, 2
        order by total desc
        limit 10
      ) m
    ), '[]'::jsonb),
    'location_breakdown', coalesce((
      select jsonb_agg(to_jsonb(l))
      from (
        select coalesce(nullif(city, ''), 'Unknown city') as city,
          coalesce(nullif(region, ''), 'Unknown region') as region,
          coalesce(nullif(country, ''), nullif(country_code, ''), 'Unknown country') as country,
          count(*)::integer as total
        from public.visitor_events
        group by 1, 2, 3
        order by total desc
        limit 10
      ) l
    ), '[]'::jsonb),
    'top_pages', coalesce((
      select jsonb_agg(to_jsonb(p))
      from (
        select path, count(*)::integer as total
        from public.visitor_events
        group by path
        order by total desc
        limit 8
      ) p
    ), '[]'::jsonb)
  );
end
$$;

create or replace function public.dashboard_inquiry(p_token text, p_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not private.dashboard_token_ok(p_token) then
    raise exception 'unauthorized';
  end if;

  select to_jsonb(i) || jsonb_build_object(
    'messages', coalesce((
      select jsonb_agg(to_jsonb(m) order by m.created_at desc)
      from public.inquiry_messages m
      where m.inquiry_id = i.id
    ), '[]'::jsonb)
  )
  into result
  from public.project_inquiries i
  where i.id = p_id;

  return result;
end
$$;

create or replace function public.dashboard_record_notification(
  p_token text,
  p_id bigint,
  p_message_type text,
  p_subject text,
  p_body text,
  p_delivery_status text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.dashboard_token_ok(p_token) then
    raise exception 'unauthorized';
  end if;
  if p_message_type not in ('receipt', 'accepted', 'declined', 'reply', 'status') then
    raise exception 'invalid_message_type';
  end if;
  if p_delivery_status not in ('sent', 'not-configured', 'not-applicable', 'failed') then
    raise exception 'invalid_delivery_status';
  end if;
  if char_length(coalesce(p_body, '')) > 10000 then
    raise exception 'message_too_long';
  end if;

  insert into public.inquiry_messages (inquiry_id, message_type, subject, body, delivery_status)
  values (p_id, p_message_type, left(coalesce(p_subject, ''), 220), coalesce(p_body, ''), p_delivery_status);

  update public.project_inquiries
  set client_response = case when p_message_type = 'reply' then coalesce(p_body, '') else client_response end,
      last_notification_status = p_delivery_status,
      last_notified_at = case when p_delivery_status = 'sent' then now() else last_notified_at end,
      updated_at = now()
  where id = p_id;

  return found;
end
$$;

revoke execute on function public.dashboard_record_notification(text, bigint, text, text, text, text)
from public, authenticated, service_role;
grant execute on function public.dashboard_record_notification(text, bigint, text, text, text, text)
to anon;

